# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
notify:
  webhooks:
    - url: https://cljdoc.xyz/api/hooks/circle-ci

jobs:
  build:
    docker:
      # specify the version you desire here
      # reference:
      # https://circleci.com/docs/2.0/configuration-reference/#docker--machine--macosexecutor
      - image: circleci/clojure:tools-deps
        command: "/bin/bash"

    environment:
      CLJDOC_REPO: https://github.com/martinklepsch/cljdoc.git
      VERSION_FALLBACK: 65404db681e14acda5e5bee74e6d56403177e2b6

    steps:
      # Env vars cannot be used for cache keys so we put
      # it in a file and use the checksum of that file
      # https://discuss.circleci.com/t/10994/9
      - run: echo ${CLJDOC_ANALYZER_VERSION:-$VERSION_FALLBACK} > /tmp/cache-key

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "/tmp/cache-key" }}
          - v1-dependencies- # fallback if not cache found

      - run:
          name: Download cljdoc code
          working_directory: ~/
          command: |
            rm -rf cljdoc
            curl -L https://github.com/martinklepsch/cljdoc/archive/${CLJDOC_ANALYZER_VERSION:-$VERSION_FALLBACK}.zip -o cljdoc.zip
            unzip cljdoc.zip
            mv -f cljdoc-${CLJDOC_ANALYZER_VERSION:-$VERSION_FALLBACK} cljdoc

      # - run:
      #     name: Clone cljdoc repo
      #     command: if cd cljdoc; then git pull; else git clone $CLJDOC_REPO; fi
      #     working_directory: ~/

      # - run:
      #     name: Checkout cljdoc repo
      #     command: git checkout $CLJDOC_ANALYZER_VERSION
      #     working_directory: ~/cljdoc

      - run:
          name: Print build parameters
          command: echo "$CLJDOC_PROJECT $CLJDOC_PROJECT_VERSION" "$CLJDOC_PROJECT_JAR"

      - run:
          name: Run analysis
          command: ./script/analyze.sh ${CLJDOC_PROJECT:-$PROJECT_FALLBACK} ${CLJDOC_PROJECT_VERSION:-$PROJECT_VERSION_FALLBACK} ${CLJDOC_PROJECT_JAR:-$PROJECT_JAR_FALLBACK} ${CLJDOC_PROJECT_POM:-$PROJECT_POM_FALLBACK}
          environment:
            - PROJECT_FALLBACK: bidi
            - PROJECT_VERSION_FALLBACK: 2.1.3
            - PROJECT_JAR_FALLBACK: https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.jar
            - PROJECT_POM_FALLBACK: https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.pom
          working_directory: ~/cljdoc

      - store_artifacts:
          path: /tmp/cljdoc/analysis-out/
          destination: /

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "/tmp/cache-key" }}
