version: 2.1
parameters:
  # Fallbacks are for sanity testing changes to builder itself, cljdoc should always pass in valid parameters
  cljdoc-analyzer-dep:
    type: string
    default: '{:deps {cljdoc-analyzer {:git/url "https://github.com/cljdoc/cljdoc-analyzer.git" :sha "f1ef5d452266cd912559109c6653cd4b8e29b8fc"}}}'
  cljdoc-analyzer-args:
    type: string
    default: '{:project "bidi" :version "2.1.3" :jarpath "https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.jar" :pompath "https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.pom"}'

jobs:
  build:
    docker:
      - image: clojure:temurin-24-tools-deps-noble

    steps:
      - run:
          name: Setup for cache
          command: echo '<< pipeline.parameters.cljdoc-analyzer-dep >>' > /tmp/cache-key

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "/tmp/cache-key" }}
          - v1-dependencies- # fallback if not cache found

      - run:
          name: Dump tools versions
          command: |
            echo java -version
            java -version
            echo clojure -Sdescribe
            clojure -Sdescribe

      - run:
          name: Print build parameters
          command: echo '<< pipeline.parameters.cljdoc-analyzer-args >>'

      - run:
          name: Run analysis
          command: >
            clojure -Sdeps '<< pipeline.parameters.cljdoc-analyzer-dep >>'
            -M -m cljdoc-analyzer.cljdoc-main
            '<< pipeline.parameters.cljdoc-analyzer-args >>'

      - store_artifacts:
          # WARNING: this path must match cljdoc-shared.analysis/output-prefix
          path: /tmp/cljdoc/analysis-out/
          destination: /

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "/tmp/cache-key" }}
