# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # reference:
      # https://circleci.com/docs/2.0/configuration-reference/#docker--machine--macosexecutor
      - image: circleci/clojure:tools-deps
        command: "/bin/bash"

    environment:
      CLJDOC_REPO: https://github.com/cljdoc/cljdoc.git
      VERSION_FALLBACK: 4594c63126039ef879655a77e85dc47ed90c3932

    steps:
      # Env vars cannot be used for cache keys so we put
      # it in a file and use the checksum of that file
      # https://discuss.circleci.com/t/10994/9
      - run: echo ${CLJDOC_ANALYZER_VERSION:-$VERSION_FALLBACK} > /tmp/cache-key

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "/tmp/cache-key" }}
          - v1-dependencies- # fallback if not cache found

      - run:
          name: Download cljdoc code
          working_directory: ~/
          command: |
            rm -rf cljdoc
            curl -L https://github.com/cljdoc/cljdoc/archive/${CLJDOC_ANALYZER_VERSION:-$VERSION_FALLBACK}.zip -o cljdoc.zip
            unzip cljdoc.zip
            mv -f cljdoc-${CLJDOC_ANALYZER_VERSION:-$VERSION_FALLBACK} cljdoc

      - run:
          name: Print build parameters
          command: echo "$CLJDOC_ANALYZER_ARGS"

      - run:
          name: Run analysis
          command: clojure -m cljdoc.analysis.runner-ng ${CLJDOC_ANALYZER_ARGS:-FALLBACK}
          environment:
            - FALLBACK: '{:project "bidi" :version "2.1.3" :jarpath "https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.jar" :pompath "https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.pom"}'
          working_directory: ~/cljdoc/modules/analysis-runner

      - store_artifacts:
          path: /tmp/cljdoc/analysis-out/
          destination: /

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "/tmp/cache-key" }}
