# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:boot-2.7.1
        # https://discuss.circleci.com/t/builds-getting-killed-with-vague-message-received-signal-killed/10214/9
        cmd: ["/bin/bash"]

    working_directory: ~/repo

    environment:
      BOOT_JVM_OPTIONS: -Xmx2048m # Customize the JVM maximum heap limit
      CLJDOC_REPO: https://github.com/martinklepsch/cljdoc.git
      CLJDOC_ANALYZER_VERSION: 47ef2ee59d1023ddf95e45a7d57ceb81143e1df0

    # TODO implement this to be notified once a build is done
    # notify:
    #   webhooks:
    #     # A list of hook hashes, containing the URL field
    #     - url: https://example.com/hooks/circle

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-$CLJDOC_ANALYZER_VERSION
          - v1-dependencies- # fallback if not cache found

      - run:
          command: if cd cljdoc; then git pull; else git clone $CLJDOC_REPO; fi
          working_directory: ~/

      - run:
          command: git reset --hard $CLJDOC_ANALYZER_VERSION
          working_directory: ~/cljdoc

      - run:
          command: ./script/analyze.sh bidi 2.1.3 https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.jar
          working_directory: ~/cljdoc

      - store_artifacts:
          path: ~/cljdoc/target/codox-edn
          destination: /codox-edn

      - save_cache:
          paths:
            - ~/cljdoc
            - ~/.m2
            - ~/.boot
          key: v1-dependencies-$CLJDOC_ANALYZER_VERSION
