# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # reference:
      # https://circleci.com/docs/2.0/configuration-reference/#docker--machine--macosexecutor
      - image: circleci/clojure:tools-deps
        command: "/bin/bash"

    environment:
      DEP_FALLBACK: '{:deps {cljdoc-analyzer {:git/url "https://github.com/lread/cljdoc-analyzer.git" :sha "02d0ca4b982c60a5920cf391b3eb8280b4aa97dd"}}})'

    steps:
      # Env vars cannot be used for cache keys so we put
      # it in a file and use the checksum of that file
      # https://discuss.circleci.com/t/10994/9
      - run: echo ${CLJDOC_ANALYZER_DEP:-$DEP_FALLBACK} > /tmp/cache-key

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "/tmp/cache-key" }}
          - v1-dependencies- # fallback if not cache found

      - run:
          name: Print build parameters
          command: echo "$CLJDOC_ANALYZER_ARGS"

      - run:
          name: Run analysis
          command: clojure -Sdeps "${CLJDOC_ANALYZER_DEP:-$DEP_FALLBACK}" -m cljdoc-analyzer.cljdoc-main "${CLJDOC_ANALYZER_ARGS:-$FALLBACK}"
          environment:
            - FALLBACK: '{:project "bidi" :version "2.1.3" :jarpath "https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.jar" :pompath "https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.pom"}'

      - store_artifacts:
          path: /tmp/cljdoc/analysis-out/
          destination: /

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "/tmp/cache-key" }}
