version: 2.1

jobs:
  build:
    docker:
      - image: clojure:temurin-25-tools-deps-noble

    # The fallback setup is only for sanity testing, when changes are made to the builder project itself it will use fallback values.
    # When builder is triggered by cljdoc it will always pass in the appropriate arguments.
    environment:
      DEP_FALLBACK: '{:deps {cljdoc-analyzer {:git/url "https://github.com/cljdoc/cljdoc-analyzer.git" :sha "d8d2eaf4d3b60af07866cbd208ac024901caab5f"}}})'

    steps:
      # Env vars cannot be used for cache keys so we put
      # it in a file and use the checksum of that file
      - run:
          name: Setup for cache
          command: echo ${CLJDOC_ANALYZER_DEP:-$DEP_FALLBACK} > /tmp/cache-key

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "/tmp/cache-key" }}
          - v1-dependencies- # fallback if not cache found

      - run:
          name: Dump tools versions
          command: |
            echo java -version
            java -version
            echo clojure -Sdescribe
            clojure -Sdescribe

      - run:
          name: Print build parameters
          command: echo "$CLJDOC_ANALYZER_ARGS"

      - run:
          name: Run analysis
          command: clojure -Sdeps "${CLJDOC_ANALYZER_DEP:-$DEP_FALLBACK}" -M -m cljdoc-analyzer.cljdoc-main "${CLJDOC_ANALYZER_ARGS:-$FALLBACK}"
          environment:
            - FALLBACK: '{:project "bidi" :version "2.1.3" :jarpath "https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.jar" :pompath "https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.pom"}'

      - store_artifacts:
          # WARNING: this path must match cljdoc-shared.analysis/output-prefix
          path: /tmp/cljdoc/analysis-out/
          destination: /

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "/tmp/cache-key" }}
