# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
notify:
  webhooks:
    - url: http://api.cljdoc.xyz:8000/hooks/circle-ci
    - url: http://66279947.ngrok.io/hooks/circle-ci

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:boot-2.7.1
        # https://discuss.circleci.com/t/builds-getting-killed-with-vague-message-received-signal-killed/10214/9
        cmd: ["/bin/bash"]

    working_directory: ~/repo

    environment:
      BOOT_JVM_OPTIONS: -Xmx2048m # Customize the JVM maximum heap limit
      CLJDOC_REPO: https://github.com/martinklepsch/cljdoc.git
      CLJDOC_ANALYZER_VERSION: 87ab11d6a267a15156e71b95e99eb8f0edba04a5

    steps:
      - checkout

      # Env vars cannot be used for cache keys so we put
      # it in a file and use the checksum of that file
      # https://discuss.circleci.com/t/10994/9
      - run: echo "$CLJDOC_ANALYZER_VERSION" > /tmp/cache-key

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "/tmp/cache-key" }}
          - v1-dependencies- # fallback if not cache found

      - run:
          name: Clone cljdoc repo
          command: if cd cljdoc; then git pull; else git clone $CLJDOC_REPO; fi
          working_directory: ~/

      - run:
          name: Checkout cljdoc repo
          command: git reset --hard $CLJDOC_ANALYZER_VERSION
          working_directory: ~/cljdoc

      - run:
          name: Print build parameters
          command: echo "$CLJDOC_PROJECT $CLJDOC_PROJECT_VERSION" "$CLJDOC_PROJECT_JAR"

      - run:
          name: Run analysis
          command: ./script/analyze.sh ${CLJDOC_PROJECT:-$PROJECT_FALLBACK} ${CLJDOC_PROJECT_VERSION:-$PROJECT_VERSION_FALLBACK} ${CLJDOC_PROJECT_JAR:-$PROJECT_JAR_FALLBACK}
          environment:
            - PROJECT_FALLBACK: bidi
            - PROJECT_VERSION_FALLBACK: 2.1.3
            - PROJECT_JAR_FALLBACK: https://repo.clojars.org/bidi/bidi/2.1.3/bidi-2.1.3.jar
          working_directory: ~/cljdoc

      - store_artifacts:
          path: /tmp/cljdoc-target/cljdoc-edn
          destination: /cljdoc-edn

      - save_cache:
          paths:
            - ~/cljdoc
            - ~/.m2
            - ~/.boot
          key: v1-dependencies-{{ checksum "/tmp/cache-key" }}
